### ISSUE TITLE
Error on demo page

### ISSUE THREAD

**Issue by kanakiyajay** [institut-de-genomique/Ultimate-DataTable#1]
Getting this error in the console of demo page:

``` js
TypeError: Cannot read property 'datatable.button.edit' of undefined
    at Object.udtI18n.Messages (ultimate-datatable-3.1.0.js:3125)
    at Object.scope.udtTableFunctions.messagesDatatable (ultimate-datatable-3.1.0.js:2793)
    at angular-1.3.16.min.js:200
    at Object.<anonymous> (angular-1.3.16.min.js:108)
    at m.$digest (angular-1.3.16.min.js:123)
    at m.$apply (angular-1.3.16.min.js:127)
    at angular-1.3.16.min.js:139
    at e (angular-1.3.16.min.js:40)
    at angular-1.3.16.min.js:44
```

Also table count is not getting displayed correctly.

**Comment by galbini** [comment]
Thanks for your interest in ultimate datatable. we are recently change your message system and this bug is fixed in 3.2.0-SNAPSHOT version.

Can you try with this version ?

**Comment by galbini** [comment]
I tried this package : https://github.com/institut-de-genomique/Ultimate-DataTable/archive/3.1.0.zip and i have no error on chrome with the page demo/simple.html

Are you tried this page ? Which browser do you have ?

**Comment by ydeshayes** [comment]
Maybe that his language is not implemented and this may cause this error. I push a bugfix (in 3.2.0-SNAPSHOT) that replace the current language by the english one if it's not implemented in the i18n service.

**Comment by kanakiyajay** [comment]
Seems like you have not updated the gh-pages branch.
http://institut-de-genomique.github.io/Ultimate-DataTable/

**Comment by ydeshayes** [comment]
I've updated the demo website with the 3.2.0-SNAPSHOT version, you can test here:
http://institut-de-genomique.github.io/Ultimate-DataTable/

Is everything working fine now ?
