### ISSUE TITLE
Column hidden by default

### ISSUE THREAD

**Issue by Jenselme** [institut-de-genomique/Ultimate-DataTable#12]
Hi,

I just started to use Ultimate DataTable. It's awesome, thanks!

However, I searched for a way to make a column hidden by default in the configuration but I didn't find any solution. I would also like to hide/show a column programmatically.

Is it possible? If not, would it be possible to add it? I should be able to contribute if necessary.

**Comment by galbini** [comment]
Hello,

Effectively, there are no possibility to hide a column by default.

You can program this comportment.
First extract all columns after datatable configuration and then set column must be hide. see below

```
$scope.datatable = datatable(datatableConfig);
$scope.datatable.setData(datatableData);
//extract all column
var columns = $scope.datatable.getColumnsConfig();
//hide the first column.
$scope.datatable.setHideColumn(columns[0]);
```

Thanks to use UDT !
Guillaume

**Comment by Jenselme** [comment]
It's a good new that I can programmatically hide a column, I will need it. But it will be easier for me to have an option to make it hidden by default. Should I work on a patch to add this behavior?

**Comment by galbini** [comment]
Yes, I try to find a solution

**Comment by galbini** [comment]
Hello,

I add a param byDefault on hide configuration to hide default columns.
You need to put the column.property value in byDefault parameter. 

```
"hide":{
    "active":true,
    "byDefault":["about","name"]
}
```

Guillaume

**Comment by Jenselme** [comment]
Awesome, thanks!
