### ISSUE TITLE
numberRecordsPerPageList not respected for less than four items

### ISSUE THREAD

**Issue by Jenselme** [institut-de-genomique/Ultimate-DataTable#13]
If I set `numberRecordsPerPageList` to a list of two elements, for instance:

``` js
numberRecordsPerPageList: [
    {number: 5, clazz: ''},
    {number: 10, clazz: ''},
]
```

I get the following proposal for size:
- 5
- 10
- 50
- 100

But if I set my `numberRecordsPerPageList` to an array of 4 or more element, the choice is correctly respected.

**Comment by galbini** [comment]
Hello,

Thanks for your report. 
We use JQuery to merge the default config with the custom config. In case of  array property, the default property isn't fully replace but just the elements on the same position are replaced.

Today, i don't found any solution but i tries to find it !

**Comment by Jenselme** [comment]
I see where the problem is. Maybe override this by hand with:

``` js
var settings = $.extend(true, {}, this.configDefault, config);
if ($.isArray(config.pagination.numberRecordsPerPageList)) {
    settings.pagination.numberRecordsPerPageList = config.pagination.numberRecordsPerPageList;
}
this.config = angular.copy(settings);
```

What do you think?

**Comment by galbini** [comment]
Your solution works but I am not sure that's the best solution. 
Before implement your solution, I try to search another way to resolve this problem.

Thanks for your feeback.

**Comment by galbini** [comment]
I resolve the problem. Can you try please ?

**Comment by Jenselme** [comment]
It works, thanks!
