### ISSUE TITLE
Question asked via Stackoverflow

### ISSUE THREAD

**Issue by ghost** [institut-de-genomique/Ultimate-DataTable#18]
This is not exactly an issue but can't find better way to contact you guys.

I asked on SO about something considering your lib so thought you might be interested.

http://stackoverflow.com/questions/34386781/angular-directive-manual-compile-in-link-function-transclude

**Comment by galbini** [comment]
The udt-form directive is used to include html form define by the developer inside this directive.

If you remove ng-transclude this feature is no more available.

what do you want try exactly ?

**Comment by ghost** [comment]
I'm in need of providing ability to load different templates per table instance. Plus another one requirement to provide "render" functionality as it is done for "content" cells also for header cells.

**Comment by galbini** [comment]
with angular, the templateUrl parameter of directive accept a function see https://docs.angularjs.org/guide/directive.

May be can help you to have a different templates per table instance.
