### ISSUE TITLE
Hiding a column does not work

### ISSUE THREAD

**Issue by BenderNETs** [institut-de-genomique/Ultimate-DataTable#26]
I'm trying to hide a column and added the following in the config:
...
"columns": [
            {
                "property": "Id",
                "type": "text",
                "hide": true
            },
...

The Id column still shows up. Is there anything I missed?

**Comment by galbini** [comment]
Hi,

You need active the hide function in configuration, see simple.html

``` javascript
{
"hide": {"active":true}
}
```

Best Regards,
Guillaume

**Comment by BenderNETs** [comment]
Thanks Guillame :)
