### ISSUE TITLE
Access other properties of object inside 'render' of column

### ISSUE THREAD

**Issue by AviShmueli** [institut-de-genomique/Ultimate-DataTable#30]
Hi,
Can I render to column other value besides the value that I pass to the column in "property"?
what I need is to render the name of the object inside "<a>" tag that href to URL with the id of the object as a parameter.
How can I do that?

This is what i need:
`"columns": [{
                "header": "Name",
                "property": "ItemName",
                "order": true,
                "type": "text",
                "showFilter": true,
                "groupMethod": "collect",
                "render": "<a target='blank' ng-href='/Catalog/Item/#/?ItemId={{**ItemId**}}'>{{cellValue}}</a>",
                "hide": true
            },...`

Thanks.

**Comment by galbini** [comment]
Hi,

You can access at the whole object with variable "value.data" in your case : 

``` javascript
"render": "<a target='blank' ng-href='/Catalog/Item/#/?ItemId={{value.data.ItemId}}'>{{cellValue}}</a>"
```

Best regards,
Guillaume

**Comment by AviShmueli** [comment]
Thank you, man!
Great tool, by the way...
