### ISSUE TITLE
mouseevent.clickCallBack does not execute when all rows are selected.

### ISSUE THREAD

**Issue by jcraney** [institut-de-genomique/Ultimate-DataTable#48]
When I select all of the rows using the button at the top of the data table, the mouseevent.clickCallback is never called. There is no explanation of how to access all of the selected lines and their data when using the select all control button. The Documentation says that the select callback was deprecated for the mouseevent.clickCallBack but I need to access all of the lines that have been selected and then get the data from those lines inside the clickCallBack.

**Comment by galbini** [comment]
The mouseevent.clickCallback is now available when select all lines.
